; Auto-generated. Do not edit!


(in-package schunkarm_server-msg)


;//! \htmlinclude movearmFeedback.msg.html

(defclass <movearmFeedback> (ros-message)
  ((current_pose
    :reader current_pose-val
    :initarg :current_pose
    :type geometry_msgs-msg:<Pose>
    :initform (make-instance 'geometry_msgs-msg:<Pose>)))
)
(defmethod serialize ((msg <movearmFeedback>) ostream)
  "Serializes a message object of type '<movearmFeedback>"
  (serialize (slot-value msg 'current_pose) ostream)
)
(defmethod deserialize ((msg <movearmFeedback>) istream)
  "Deserializes a message object of type '<movearmFeedback>"
  (deserialize (slot-value msg 'current_pose) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<movearmFeedback>)))
  "Returns string type for a message object of type '<movearmFeedback>"
  "schunkarm_server/movearmFeedback")
(defmethod md5sum ((type (eql '<movearmFeedback>)))
  "Returns md5sum for a message object of type '<movearmFeedback>"
  "8aa49ba45d5b9d2df8a650fff8d23e31")
(defmethod message-definition ((type (eql '<movearmFeedback>)))
  "Returns full string definition for message of type '<movearmFeedback>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#Feedback~%geometry_msgs/Pose current_pose~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(defmethod serialization-length ((msg <movearmFeedback>))
  (+ 0
     (serialization-length (slot-value msg 'current_pose))
))
(defmethod ros-message-to-list ((msg <movearmFeedback>))
  "Converts a ROS message object to a list"
  (list '<movearmFeedback>
    (cons ':current_pose (current_pose-val msg))
))
