; Auto-generated. Do not edit!


(in-package schunkarm_server-msg)


;//! \htmlinclude movearmGoal.msg.html

(defclass <movearmGoal> (ros-message)
  ((goal_pose
    :reader goal_pose-val
    :initarg :goal_pose
    :type geometry_msgs-msg:<Pose>
    :initform (make-instance 'geometry_msgs-msg:<Pose>)))
)
(defmethod serialize ((msg <movearmGoal>) ostream)
  "Serializes a message object of type '<movearmGoal>"
  (serialize (slot-value msg 'goal_pose) ostream)
)
(defmethod deserialize ((msg <movearmGoal>) istream)
  "Deserializes a message object of type '<movearmGoal>"
  (deserialize (slot-value msg 'goal_pose) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<movearmGoal>)))
  "Returns string type for a message object of type '<movearmGoal>"
  "schunkarm_server/movearmGoal")
(defmethod md5sum ((type (eql '<movearmGoal>)))
  "Returns md5sum for a message object of type '<movearmGoal>"
  "703d9fa1b50df73e1eb3a62a925392a1")
(defmethod message-definition ((type (eql '<movearmGoal>)))
  "Returns full string definition for message of type '<movearmGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%geometry_msgs/Pose goal_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(defmethod serialization-length ((msg <movearmGoal>))
  (+ 0
     (serialization-length (slot-value msg 'goal_pose))
))
(defmethod ros-message-to-list ((msg <movearmGoal>))
  "Converts a ROS message object to a list"
  (list '<movearmGoal>
    (cons ':goal_pose (goal_pose-val msg))
))
