; Auto-generated. Do not edit!


(in-package schunkarm_server-msg)


;//! \htmlinclude movearmGoal.msg.html

(defclass <movearmGoal> (ros-message)
  ((goal_pose
    :reader goal_pose-val
    :initarg :goal_pose
    :type geometry_msgs-msg:<PoseStamped>
    :initform (make-instance 'geometry_msgs-msg:<PoseStamped>)))
)
(defmethod serialize ((msg <movearmGoal>) ostream)
  "Serializes a message object of type '<movearmGoal>"
  (serialize (slot-value msg 'goal_pose) ostream)
)
(defmethod deserialize ((msg <movearmGoal>) istream)
  "Deserializes a message object of type '<movearmGoal>"
  (deserialize (slot-value msg 'goal_pose) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<movearmGoal>)))
  "Returns string type for a message object of type '<movearmGoal>"
  "schunkarm_server/movearmGoal")
(defmethod md5sum ((type (eql '<movearmGoal>)))
  "Returns md5sum for a message object of type '<movearmGoal>"
  "6815aa242b5054bf4354bc4502009b6d")
(defmethod message-definition ((type (eql '<movearmGoal>)))
  "Returns full string definition for message of type '<movearmGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%geometry_msgs/PoseStamped goal_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: roslib/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(defmethod serialization-length ((msg <movearmGoal>))
  (+ 0
     (serialization-length (slot-value msg 'goal_pose))
))
(defmethod ros-message-to-list ((msg <movearmGoal>))
  "Converts a ROS message object to a list"
  (list '<movearmGoal>
    (cons ':goal_pose (goal_pose-val msg))
))
